# Generated by Django 5.2.8 on 2025-11-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='kilometros',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='auto',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
