# Generated by Django 5.2.8 on 2025-11-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_kilometros_auto_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='kilometros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
